services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  postgres_data:
