FROM node:22-slim

RUN npm install -g pnpm

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./packages.json ./packages.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN pnpm install
RUN cd packages/db && pnpm prisma generate && cd ../..
RUN DATABASE_URL=${DATABASE_URL} pnpm run build

EXPOSE 3000

CMD ["pnpm","start"]